name: groceries_app_backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bcrypt: ^1.1.3
  build_runner: ^2.4.8
  dart_frog: ^1.1.0
  dart_jsonwebtoken: ^2.13.0
  dartz: ^0.10.1
  dotenv: ^4.2.0
  get_it: ^7.6.7
  googleapis: ^12.0.0
  googleapis_auth: ^1.5.0
  http: ^1.2.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  orm: ^5.0.5
  otp: ^3.1.4
  redis: ^4.0.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^6.0.0
